version: "3.7"

services:
  nginx_service:
    build:
      context: ./main_nginx
      target: reverse_proxy
    container_name: proxy-main
    depends_on:
      - node_service
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      main_network:
        ipv4_address: 172.20.1.2

  node_service:
    build:
      context: ./main_node
      target: web_main
    container_name: web-main
    ports:
      - '8080:8080'
    networks:
      main_network:
        ipv4_address: 172.20.1.3

networks:
  main_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.1
